name: Dockerhub

on:
  push:
    branches: main

jobs:
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install and Build 🔧
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Install Dependencies
        run: npm install
        working-directory: ./client
      - name: Build
        run: npm run build
        working-directory: ./client
        env:
          CI: false
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: |
            ./client/build
  build-and-deploy:
    name: Build and Deploy Docker
    needs: build-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: client
          path: client-build
      - run: ls -la
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hamzaabamboo/video-clipper:latest
          file: Dockerfile.actions
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
